version: '3.8'

services:
  backend:
    image: lukas05/myapp-backend:latest
    pull_policy: always
    container_name: memories-backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=memories_db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ORIGINS=https://robinenlukas.nl,http://robinenlukas.nl
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db
    # Ports removed because nginx proxies to it internally
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    image: lukas05/myapp-frontend:latest
    pull_policy: always
    container_name: memories-frontend
    depends_on:
      - backend
    # Ports removed because nginx proxies to it internally
    expose:
      - "80"
    restart: unless-stopped

  portfolio-backend:
    image: lukas05/portfolio-backend:latest
    pull_policy: always
    container_name: portfolio-backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=portfolio_db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ORIGINS=https://lukasportfolio.site,http://lukasportfolio.site
      - APP_BASE_URL=https://lukasportfolio.site/api
    depends_on:
      - db
    volumes:
      - portfolio-uploads:/app/uploads
    expose:
      - "8080"
    restart: unless-stopped

  portfolio-frontend:
    image: lukas05/portfolio-frontend:latest
    pull_policy: always
    container_name: portfolio-frontend
    depends_on:
      - portfolio-backend
    expose:
      - "80"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_DB=memories_db
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - frontend
      - backend
      - portfolio-frontend
      - portfolio-backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

volumes:
  uploads:
  portfolio-uploads:
  db-data:
